### ISSUE TITLE
Is the date format correct?

### ISSUE THREAD

**Issue by grad0x** [michalkuncio/frontendhistory#9]
Is the month and day reversed here?

<img width="942" alt="image" src="https://github.com/michalkuncio/frontendhistory/assets/31891883/9256f0d1-7e3d-4212-934c-f72803ed846a">

**Comment by grad0x** [comment]
Alright, I might have made a mistake, the format here is 'DD.MM'.

**Comment by michalkuncio** [comment]
Yes, indeed it is DD.MM, thanks for checking tho! 🫡
